# Generated by Django 3.2.8 on 2021-12-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
