# Generated by Django 3.2.8 on 2021-12-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideapp', '0002_auto_20211201_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=5000)),
                ('tags', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
