# Generated by Django 3.2.8 on 2022-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideapp', '0006_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hint',
            field=models.CharField(default='', max_length=100),
        ),
    ]
