# Generated by Django 3.2.8 on 2022-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideapp', '0007_post_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
