# Generated by Django 3.2.8 on 2021-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideapp', '0003_auto_20211215_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='極速車神大佬', max_length=100),
        ),
    ]
